#!/usr/bin/env python3
"""build_lure.py — SOLVED virus-lure routing (Tier-1 v3).

Literature check (2026-07-16): RL agents fail to learn virus-weaponization
(arxiv 2505.18347 mini-game: no agent learned lure->pop->absorb). Solved
offline here instead: while a BIGGER blob pursues us, route so its pursuit
path crosses a virus — the engine pops the LARGEST overlapping blob (16-way
fragment), converting the predator into edible pieces.

Threat model: GREEDY pure pursuit (chasers that actually chase; an optimal
pursuer that declines the lure has, by definition, stopped chasing = escape).
State (open-field frame, virus at ORIGIN): our offset from virus (ox, oy),
pursuer offset from virus (px, py), each axis 9 buckets. Value: pursuer pops
within horizon (reward 10) discounted; getting caught = 0; survival drift
small positive. Action: 8 headings. VI horizon 20.

Output: policy + value tables embedded between VL_TABLE markers.
"""
import base64, math, re, sys
from pathlib import Path

BODY = Path(__file__).resolve().parent.parent / "bots" / "omni_mixer_v3.py"

AX = [-8.0, -5.0, -3.0, -1.5, 0.0, 1.5, 3.0, 5.0, 8.0]
NA = len(AX)
H = 20
OUR_SPEED = 0.948
PUR_SPEED = 0.809         # engine law, r~4.5 chaser (2026-07-16 fix)
CAP_R = 3.0               # pursuer capture radius
VIRUS_R = 1.5             # engine virus radius; pursuer radius ~3 -> pop overlap ~3
POP_R = 2.6               # pursuer center within this of virus center => pops
DIRS = [(math.cos(a), math.sin(a)) for a in [i * math.pi / 4 for i in range(8)]]

def bucket(v, edges):
    lo, hi = 0, len(edges) - 1
    if v <= edges[0]: return 0
    if v >= edges[hi]: return hi
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if edges[mid] <= v: lo = mid
        else: hi = mid
    return lo

NSTATE = NA * NA * NA * NA
def sidx(iox, ioy, ipx, ipy):
    return ((iox * NA + ioy) * NA + ipx) * NA + ipy

def step(iox, ioy, ipx, ipy, a):
    ox, oy = AX[iox], AX[ioy]
    px, py = AX[ipx], AX[ipy]
    axx, ayy = DIRS[a]
    nox, noy = ox + axx * OUR_SPEED, oy + ayy * OUR_SPEED
    # greedy pursuit: straight at our NEW position
    dx, dy = nox - px, noy - py
    m = math.hypot(dx, dy)
    ux, uy = (dx / m, dy / m) if m > 1e-9 else (0.0, 0.0)
    npx, npy = px + ux * PUR_SPEED, py + uy * PUR_SPEED
    if math.hypot(npx, npy) <= POP_R:
        return "POP", None
    if math.hypot(npx - nox, npy - noy) <= CAP_R:
        return "CAUGHT", None
    return "GO", (bucket(nox, AX), bucket(noy, AX), bucket(npx, AX), bucket(npy, AX))

def solve():
    V = [0.0] * NSTATE
    pol = [0] * NSTATE
    for it in range(H):
        NV = [0.0] * NSTATE
        for iox in range(NA):
            for ioy in range(NA):
                for ipx in range(NA):
                    for ipy in range(NA):
                        best, barg = -1e18, 0
                        for a in range(8):
                            r, ns = step(iox, ioy, ipx, ipy, a)
                            if r == "POP":
                                val = 10.0
                            elif r == "CAUGHT":
                                val = -10.0
                            else:
                                val = 0.05 + 0.95 * V[sidx(*ns)]
                            if val > best:
                                best, barg = val, a
                        i = sidx(iox, ioy, ipx, ipy)
                        NV[i] = best
                        pol[i] = barg
        V = NV
        print(f"  VI iter {it+1}/{H}  mean value {sum(V)/len(V):.3f}", flush=True)
    return V, pol

def main():
    print(f"solving {NSTATE} lure states x 8 actions, horizon {H} ...")
    V, pol = solve()
    packed = bytearray()
    for i in range(0, len(pol), 2):
        packed.append(pol[i] | ((pol[i + 1] if i + 1 < len(pol) else 0) << 4))
    pol_b85 = base64.b85encode(bytes(packed)).decode()
    # value byte per state (0..255 scaled from [-10,10]) so runtime can demand
    # a minimum lure value before engaging
    vb = bytes(max(0, min(255, int((v + 10.0) / 20.0 * 255))) for v in V)
    val_b85 = base64.b85encode(vb).decode()
    print(f"policy {len(pol_b85)} chars, values {len(val_b85)} chars")

    # sanity: us just past virus, pursuer behind us in line -> policy should
    # NOT be pure flight; value should be high (pop imminent under pursuit)
    i = sidx(bucket(1.5, AX), bucket(0.0, AX), bucket(5.0, AX), bucket(0.0, AX))
    print(f"sanity value in-line-lure state: {V[i]:.2f} (expect strongly positive)")
    assert V[i] > 3.0
    if "--check-only" in sys.argv:
        return

    block = (
        "# VL_TABLE_BEGIN (auto-generated by tools/build_lure.py — do not edit)\n"
        "# Solved virus-lure routing vs greedy pursuit (RL agents fail to learn\n"
        "# this per arxiv 2505.18347; solved exactly here). Frame: virus at\n"
        "# origin; state = (our offset, pursuer offset).\n"
        f"_VL_AX = {AX}\n"
        f'_VL_POL_B85 = "{pol_b85}"\n'
        f'_VL_VAL_B85 = "{val_b85}"\n'
        "import base64 as _vl_b64\n"
        "_VL_POL = _vl_b64.b85decode(_VL_POL_B85)\n"
        "_VL_VAL = _vl_b64.b85decode(_VL_VAL_B85)\n"
        "def _vl_bucket(v, edges):\n"
        "    lo, hi = 0, len(edges) - 1\n"
        "    if v <= edges[0]: return 0\n"
        "    if v >= edges[hi]: return hi\n"
        "    while hi - lo > 1:\n"
        "        mid = (lo + hi) // 2\n"
        "        if edges[mid] <= v: lo = mid\n"
        "        else: hi = mid\n"
        "    return lo\n"
        "def _vl_lookup(ox, oy, px, py):\n"
        "    i = ((_vl_bucket(ox, _VL_AX) * 9 + _vl_bucket(oy, _VL_AX)) * 9\n"
        "         + _vl_bucket(px, _VL_AX)) * 9 + _vl_bucket(py, _VL_AX)\n"
        "    b = _VL_POL[i >> 1]\n"
        "    a = (b >> 4) if (i & 1) else (b & 15)\n"
        "    return a & 7, _VL_VAL[i]\n"
        "# VL_TABLE_END\n"
    )
    src = BODY.read_text()
    if "# VL_TABLE_BEGIN" in src:
        src = re.sub(r"# VL_TABLE_BEGIN.*?# VL_TABLE_END\n", block, src, flags=re.S)
    else:
        src = src.replace("# EV_TABLE_BEGIN", block + "\n# EV_TABLE_BEGIN", 1)
    BODY.write_text(src)
    print(f"embedded VL table into {BODY.name}")

if __name__ == "__main__":
    main()
