#!/usr/bin/env python3
"""CODEGEN: constant-fold CONFIG lookups into literals for speed.
Mode-aware: keys touched by any MODE_OVERLAYS diff stay dynamic (dict lookups),
everything else folds to its literal value. Behavior-identical by construction;
verify with verify_moves/equiv_test. Usage: codegen.py <in.py> <out.py>"""
import ast, re, sys
from pathlib import Path

def main(inp, outp):
    src = Path(inp).read_text()
    m = re.search(r"CONFIG\s*=\s*\{(.*?)\n\}", src, re.S)
    cfg = ast.literal_eval("{" + m.group(1) + "\n}")
    cfg_end = m.end()
    ov = re.search(r"MODE_OVERLAYS\s*=\s*(\{.*?\})\s*\n", src)
    overlays = ast.literal_eval(ov.group(1)) if ov else {}
    dynamic = set()
    for d in overlays.values():
        dynamic |= set(d.keys())
    head, body = src[:cfg_end], src[cfg_end:]
    folded = kept = 0
    def lit(v):
        return repr(v)
    def sub_index(mm):
        nonlocal folded, kept
        k = mm.group(1)
        if k in cfg and k not in dynamic and isinstance(cfg[k], (int, float)) and not isinstance(cfg[k], bool):
            folded += 1
            return lit(cfg[k])
        kept += 1
        return mm.group(0)
    body = re.sub(r'CONFIG\["([A-Za-z0-9_]+)"\]', sub_index, body)
    def sub_get(mm):
        nonlocal folded, kept
        k = mm.group(1)
        if k in cfg and k not in dynamic and isinstance(cfg[k], (int, float)) and not isinstance(cfg[k], bool):
            folded += 1
            return lit(cfg[k])
        kept += 1
        return mm.group(0)
    body = re.sub(r'CONFIG\.get\("([A-Za-z0-9_]+)",\s*[^)]+\)', sub_get, body)
    out = head + body
    banner = f'"""CODEGEN build — {folded} CONFIG lookups constant-folded, {kept} kept dynamic (mode-overlay keys). Behavior-identical; generated by tools/codegen.py."""\n'
    out = banner + out
    Path(outp).write_text(out)
    print(f"codegen: folded {folded}, dynamic kept {kept} -> {outp}")

if __name__ == "__main__":
    main(*sys.argv[1:3])
